import ContainerPrinc from '../components/LayoutFolder/Layout';
import Providers from './Providers'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <ContainerPrinc>
            {children}
          </ContainerPrinc>
        </Providers>
      </body>
    </html>
  );
}

